version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/grades2
      - ~/.ssh:/root/.ssh
      - node-modules:/usr/src/app/node_modules
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  node-modules: